version: "3"

services:
  web:
    environment:
      DJANGO_DEBUG: "True"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_HOST: "db"
      DJANGO_WEB_HOST: "web"
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  nginx:
    ports:
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./mysite/static:/code/static
    environment:
      DJANGO_WEB_HOST: "web"

  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
